version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: go_scrum_poker_bot_local
    command: ./app
    ports:
      - 8000:8000
    environment:
      SLACK_TOKEN: "FILL ME"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
