name: Lint, Tests, Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
          args: -D errcheck
      - name: Run tests
        run: |
          go test ./... -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -tags=test
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build .
